version: "3"

volumes:
  redis_data:
    driver: local
  pg_data:


services:
  postgres:
    image: postgres:alpine3.18
    restart: unless-stopped
    ports:
      - "5429:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
      POSTGRES_DB: db

  redis:
    image: redis:7.0.11-alpine
    restart: unless-stopped
    ports:
      - "6329:6379"
    command: "redis-server --requirepass redis --appendonly yes"
    volumes:
      - redis_data:/data
